---
name: tfsec
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tfsec:
    name: tfsec scan
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Run tfsec and generate SARIF report
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif

      - name: Convert SARIF to JSON
        run: cat tfsec.sarif | jq '.' > tfsec-results.json

      - name: Upload tfsec scan results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: tfsec-results
          path: tfsec-results.json
